In [4]:
import numpy

# Parameter initialization 
genes = 2
chromosomes = 10
mattingPoolSize = 6
offspringSize = chromosomes - mattingPoolSize
lb = -5
ub = 5
populationSize = (chromosomes, genes)
generations = 3

#Population initialization
population = numpy.random.uniform(lb, ub, populationSize)

for generation in range(generations):
    print(("Generation:", generation + 1))
    fitness = numpy.sum(population*population, axis=1)
    print("\npopulation")
    print(population)
    print("\nfitness calcuation")
    print(fitness)
    # Following statement will create an empty two dimensional array to store parents
    parents = numpy.empty((mattingPoolSize, population.shape[1]))

    # A loop to extract one parent in each iteration
    for p in range(mattingPoolSize):
        # Finding index of fittest chromosome in the population
        fittestIndex = numpy.where(fitness == numpy.max(fitness))
        # Extracting index of fittest chromosome
        fittestIndex = fittestIndex[0][0]
        # Copying fittest chromosome into parents array
        parents[p, :] = population[fittestIndex, :]
        # Changing fitness of fittest chromosome to avoid reselection of that chromosome 
        fitness[fittestIndex] = -1
    print("\nParents:")
    print(parents)

    # Following statement will create an empty two dimensional array to store offspring
    offspring = numpy.empty((offspringSize, population.shape[1]))
    for k in range(offspringSize):
        #Determining the crossover point
        crossoverPoint = numpy.random.randint(0,genes) 

        # Index of the first parent.
        parent1Index = k%parents.shape[0]

        # Index of the second.
        parent2Index = (k+1)%parents.shape[0]

        # Extracting first half of the offspring
        offspring[k, 0: crossoverPoint] = parents[parent1Index, 0: crossoverPoint]

        # Extracting second half of the offspring
        offspring[k, crossoverPoint:] = parents[parent2Index, crossoverPoint:]

    print("\nOffspring after crossover:")
    print(offspring)

    # Implementation of random initialization mutation. 
    for index in range(offspring.shape[0]):
        randomIndex = numpy.random.randint(1,genes)
        randomValue = numpy.random.uniform(lb, ub, 1)
        offspring [index, randomIndex] = offspring [index, randomIndex] + randomValue
    print("\n Offspring after Mutation")
    print(offspring)

    population[0:parents.shape[0], :] = parents
    population[parents.shape[0]:, :] = offspring
    print("\nNew Population for next generation:")
    print(population)

fitness = numpy.sum(population*population, axis=1)
fittestIndex = numpy.where(fitness == numpy.max(fitness))
# Extracting index of fittest chromosome
fittestIndex = fittestIndex[0][0]
# Getting Best chromosome
fittestInd = population[fittestIndex, :]
bestFitness = fitness[fittestIndex]
print("\nBest Individual:")
print(fittestInd)
print("\nBest Individual's Fitness:")
print(bestFitness)

('Generation:', 1)

population
[[ 2.86025721 -1.91903358]
 [-0.58501825 -1.00163888]
 [-1.44567479 -0.80755931]
 [-1.57364058  2.03027142]
 [ 2.0017704   4.99523854]
 [ 3.4314916  -4.30023359]
 [ 1.57433565  1.77965739]
 [ 4.42304753  1.79396337]
 [-1.8538077   0.60004948]
 [ 3.37089904 -2.78783436]]

fitness calcuation
[11.86376121  1.3455268   2.74212765  6.59834672 28.95949285 30.26714352
  5.64571316 22.78165403  3.79666237 19.1349808 ]

Parents:
[[ 3.4314916  -4.30023359]
 [ 2.0017704   4.99523854]
 [ 4.42304753  1.79396337]
 [ 3.37089904 -2.78783436]
 [ 2.86025721 -1.91903358]
 [-1.57364058  2.03027142]]

Offspring after crossover:
[[ 3.4314916   4.99523854]
 [ 4.42304753  1.79396337]
 [ 3.37089904 -2.78783436]
 [ 2.86025721 -1.91903358]]

 Offspring after Mutation
[[ 3.4314916   1.80451244]
 [ 4.42304753 -1.61392621]
 [ 3.37089904 -4.54356971]
 [ 2.86025721 -4.22227648]]

New Population for next generation:
[[ 3.4314916  -4.30023359]
 [ 2.0017704   4.99523854]
 [ 4.42304753  1.7

C:\Users\24746\AppData\Local\Temp\ipykernel_11144\146535008.py:64: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  offspring [index, randomIndex] = offspring [index, randomIndex] + randomValue
